---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "008"

# Load cell
cell_serial_number: "748533"
# Sensitivity (mV/V)
cell_sensitivity: 1.604

# Encoder limit
encoder_limit_extend: 1757594
encoder_limit_retract: -1757594

# Displacement data (m)
displacement_limit_extend: 0.0107688
displacement_limit_retract: 0.0022002
displacement_range: 0.0085686

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9971259904e-05
# Encoder (count/step)
gain_step_to_count: 8.18967220755006
