---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "004"

# Load cell
cell_serial_number: "748527"
# Sensitivity (mV/V)
cell_sensitivity: 1.59858

# Encoder limit
encoder_limit_extend: 1693164
encoder_limit_retract: -1693164

# Displacement data (m)
displacement_limit_extend: 0.0104783
displacement_limit_retract: 0.0022203
displacement_range: 0.008258

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9975806452e-05
# Encoder (count/step)
gain_step_to_count: 8.19364677419355
