---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "003"

# Load cell
cell_serial_number: "749019"
# Sensitivity (mV/V)
cell_sensitivity: 1.58741

# Encoder limit
encoder_limit_extend: 1666254
encoder_limit_retract: -1667049

# Displacement data (m)
displacement_limit_extend: 0.01054
displacement_limit_retract: 0.0024122
displacement_range: 0.0081278

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9970824455e-05
# Encoder (count/step)
gain_step_to_count: 8.18931071223672
