---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "005"

# Load cell
cell_serial_number: "749017"
# Sensitivity (mV/V)
cell_sensitivity: 1.60113

# Encoder limit
encoder_limit_extend: 1703986
encoder_limit_retract: -1703069

# Displacement data (m)
displacement_limit_extend: 0.0105726
displacement_limit_retract: 0.0022652
displacement_range: 0.0083074

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9969040744e-05
# Encoder (count/step)
gain_step_to_count: 8.18947385306383
