---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "014"

# Load cell
cell_serial_number: "749038"
# Sensitivity (mV/V)
cell_sensitivity: 1.60509

# Encoder limit
encoder_limit_extend: 1769474
encoder_limit_retract: -1769474

# Displacement data (m)
displacement_limit_extend: 0.0106957
displacement_limit_retract: 0.0020688
displacement_range: 0.0086269

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9966820988e-05
# Encoder (count/step)
gain_step_to_count: 8.191875
