---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "009"

# Load cell
cell_serial_number: "750174"
# Sensitivity (mV/V)
cell_sensitivity: 1.58838

# Encoder limit
encoder_limit_extend: 1770272
encoder_limit_retract: -1770272

# Displacement data (m)
displacement_limit_extend: 0.0107811
displacement_limit_retract: 0.0021456
displacement_range: 0.0086355

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9975794018e-05
# Encoder (count/step)
gain_step_to_count: 8.18989515880356
