---
# Actuator data

# Actuator model
model: "14902-1000"
actuator_serial_number: "018"

# Load cell
cell_serial_number: "748525"
# Sensitivity (mV/V)
cell_sensitivity: 1.58036

# Encoder limit
encoder_limit_extend: 1673972
encoder_limit_retract: -1673972

# Displacement data (m)
displacement_limit_extend: 0.010131
displacement_limit_retract: 0.0019703
displacement_range: 0.0081607

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9966209598e-05
# Encoder (count/step)
gain_step_to_count: 8.19098759386223
