---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "006"

# Load cell
cell_serial_number: "749023"
# Sensitivity (mV/V)
cell_sensitivity: 1.58143

# Encoder limit
encoder_limit_extend: 1884560
encoder_limit_retract: -1884560

# Displacement data (m)
displacement_limit_extend: 0.0108912
displacement_limit_retract: 0.0017034
displacement_range: 0.0091878

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9967405476e-05
# Encoder (count/step)
gain_step_to_count: 8.18988990294076
