---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "015"

# Load cell
cell_serial_number: "750175"
# Sensitivity (mV/V)
cell_sensitivity: 1.60113

# Encoder limit
encoder_limit_extend: 1724435
encoder_limit_retract: -1724768

# Displacement data (m)
displacement_limit_extend: 0.0106834
displacement_limit_retract: 0.002275
displacement_range: 0.0084084

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9968965244e-05
# Encoder (count/step)
gain_step_to_count: 8.19042118597102
