---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "025"

# Load cell
cell_serial_number: "750166"
# Sensitivity (mV/V)
cell_sensitivity: 1.57304

# Encoder limit
encoder_limit_extend: 1658880
encoder_limit_retract: -1658880

# Displacement data (m)
displacement_limit_extend: 0.0105075
displacement_limit_retract: 0.0024199
displacement_range: 0.0080876

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9966430805e-05
# Encoder (count/step)
gain_step_to_count: 8.18889748231037
