---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "025"

# Load cell
cell_serial_number: "750178"
# Sensitivity (mV/V)
cell_sensitivity: 1.59819

# Encoder limit
encoder_limit_extend: 1679285
encoder_limit_retract: -1680245

# Displacement data (m)
displacement_limit_extend: 0.0106067
displacement_limit_retract: 0.0024163
displacement_range: 0.0081904

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9966187109e-05
# Encoder (count/step)
gain_step_to_count: 8.18929366821099
