---
# Actuator data

# Actuator model
model: "14902-1000"
actuator_serial_number: "009"

# Load cell
cell_serial_number: "748529"
# Sensitivity (mV/V)
cell_sensitivity: 1.60162

# Encoder limit
encoder_limit_extend: 1854264
encoder_limit_retract: -1854264

# Displacement data (m)
displacement_limit_extend: 0.0106868
displacement_limit_retract: 0.0016493
displacement_range: 0.0090375

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9962433707e-05
# Encoder (count/step)
gain_step_to_count: 8.1898335297584
