---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "004"

# Load cell
cell_serial_number: "749018"
# Sensitivity (mV/V)
cell_sensitivity: 1.59701

# Encoder limit
encoder_limit_extend: 1686735
encoder_limit_retract: -1685457

# Displacement data (m)
displacement_limit_extend: 0.0105514
displacement_limit_retract: 0.0023263
displacement_range: 0.0082251

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9975471545e-05
# Encoder (count/step)
gain_step_to_count: 8.18809762810651
