---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "002"

# Load cell
cell_serial_number: "749024"
# Sensitivity (mV/V)
cell_sensitivity: 1.59745

# Encoder limit
encoder_limit_extend: 1776553
encoder_limit_retract: -1777062

# Displacement data (m)
displacement_limit_extend: 0.0106357
displacement_limit_retract: 0.0019707
displacement_range: 0.008665

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9971685774e-05
# Encoder (count/step)
gain_step_to_count: 8.18977685441674
