---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "020"

# Load cell
cell_serial_number: "749029"
# Sensitivity (mV/V)
cell_sensitivity: 1.59699

# Encoder limit
encoder_limit_extend: 1845242
encoder_limit_retract: -1845242

# Displacement data (m)
displacement_limit_extend: 0.0110101
displacement_limit_retract: 0.0020109
displacement_range: 0.0089992

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9971910112e-05
# Encoder (count/step)
gain_step_to_count: 8.19070372560613
