---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "002"

# Load cell
cell_serial_number: "748520"
# Sensitivity (mV/V)
cell_sensitivity: 1.60509

# Encoder limit
encoder_limit_extend: 1687958
encoder_limit_retract: -1687958

# Displacement data (m)
displacement_limit_extend: 0.0104193
displacement_limit_retract: 0.0021903
displacement_range: 0.008229

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9965076799e-05
# Encoder (count/step)
gain_step_to_count: 8.19055133387228
