---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "014"

# Load cell
cell_serial_number: "749045"
# Sensitivity (mV/V)
cell_sensitivity: 1.59701

# Encoder limit
encoder_limit_extend: 1695768
encoder_limit_retract: -1695718

# Displacement data (m)
displacement_limit_extend: 0.0106559
displacement_limit_retract: 0.0023845
displacement_range: 0.0082714

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9972392144e-05
# Encoder (count/step)
gain_step_to_count: 8.18932871860912
