---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "026"

# Load cell
cell_serial_number: "750105"
# Sensitivity (mV/V)
cell_sensitivity: 1.58918

# Encoder limit
encoder_limit_extend: 1694446
encoder_limit_retract: -1694446

# Displacement data (m)
displacement_limit_extend: 0.0104674
displacement_limit_retract: 0.0022057
displacement_range: 0.0082617

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9965443475e-05
# Encoder (count/step)
gain_step_to_count: 8.19042290603916
