---
# Actuator data

# Actuator model
model: "14902-1000"
actuator_serial_number: "019"

# Load cell
cell_serial_number: "748526"
# Sensitivity (mV/V)
cell_sensitivity: 1.58661

# Encoder limit
encoder_limit_extend: 1719900
encoder_limit_retract: -1719900

# Displacement data (m)
displacement_limit_extend: 0.0103716
displacement_limit_retract: 0.0019869
displacement_range: 0.0083847

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9966037137e-05
# Encoder (count/step)
gain_step_to_count: 8.18856213299476
