---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "018"

# Load cell
cell_serial_number: "749042"
# Sensitivity (mV/V)
cell_sensitivity: 1.60124

# Encoder limit
encoder_limit_extend: 1828455
encoder_limit_retract: -1829257

# Displacement data (m)
displacement_limit_extend: 0.0109175
displacement_limit_retract: 0.001996
displacement_range: 0.0089215

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.996677766e-05
# Encoder (count/step)
gain_step_to_count: 8.18845693960952
