---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "015"

# Load cell
cell_serial_number: "749030"
# Sensitivity (mV/V)
cell_sensitivity: 1.57715

# Encoder limit
encoder_limit_extend: 1764469
encoder_limit_retract: -1764469

# Displacement data (m)
displacement_limit_extend: 0.0108152
displacement_limit_retract: 0.0022113
displacement_range: 0.0086039

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9970597338e-05
# Encoder (count/step)
gain_step_to_count: 8.18925100588051
