---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "016"

# Load cell
cell_serial_number: "749032"
# Sensitivity (mV/V)
cell_sensitivity: 1.59858

# Encoder limit
encoder_limit_extend: 1732199
encoder_limit_retract: -1732199

# Displacement data (m)
displacement_limit_extend: 0.0107552
displacement_limit_retract: 0.002308
displacement_range: 0.0084472

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9970838588e-05
# Encoder (count/step)
gain_step_to_count: 8.18940100882725
