---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "023"

# Load cell
cell_serial_number: "749035"
# Sensitivity (mV/V)
cell_sensitivity: 1.60279

# Encoder limit
encoder_limit_extend: 1740736
encoder_limit_retract: -1740736

# Displacement data (m)
displacement_limit_extend: 0.0107208
displacement_limit_retract: 0.0022318
displacement_range: 0.008489

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9970537533e-05
# Encoder (count/step)
gain_step_to_count: 8.19021783419529
