---
# Actuator data

# Actuator model
model: "14902-1000"
actuator_serial_number: "002"

# Load cell
cell_serial_number: "748514"
# Sensitivity (mV/V)
cell_sensitivity: 1.61386

# Encoder limit
encoder_limit_extend: 1713342
encoder_limit_retract: -1713342

# Displacement data (m)
displacement_limit_extend: 0.0103606
displacement_limit_retract: 0.0020054
displacement_range: 0.0083552

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9965588657e-05
# Encoder (count/step)
gain_step_to_count: 8.1923645634162
