---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "031"

# Load cell
cell_serial_number: "748512"
# Sensitivity (mV/V)
cell_sensitivity: 1.60926

# Encoder limit
encoder_limit_extend: 1716236
encoder_limit_retract: -1716213

# Displacement data (m)
displacement_limit_extend: 0.0106957
displacement_limit_retract: 0.0023265
displacement_range: 0.0083692

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9969518504e-05
# Encoder (count/step)
gain_step_to_count: 8.18871945881416
