---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "006"

# Load cell
cell_serial_number: "749027"
# Sensitivity (mV/V)
cell_sensitivity: 1.59164

# Encoder limit
encoder_limit_extend: 1817734
encoder_limit_retract: -1816241

# Displacement data (m)
displacement_limit_extend: 0.0107951
displacement_limit_retract: 0.0019334
displacement_range: 0.0088617

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9971490898e-05
# Encoder (count/step)
gain_step_to_count: 8.18839025124116
