---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "027"

# Load cell
cell_serial_number: "748509"
# Sensitivity (mV/V)
cell_sensitivity: 1.60776

# Encoder limit
encoder_limit_extend: 1818617
encoder_limit_retract: -1821071

# Displacement data (m)
displacement_limit_extend: 0.0107465
displacement_limit_retract: 0.0018717
displacement_range: 0.0088748

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9967084052e-05
# Encoder (count/step)
gain_step_to_count: 8.18832795981102
