---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "029"

# Load cell
cell_serial_number: "748514"
# Sensitivity (mV/V)
cell_sensitivity: 1.61386

# Encoder limit
encoder_limit_extend: 1900083
encoder_limit_retract: -1905109

# Displacement data (m)
displacement_limit_extend: 0.0111449
displacement_limit_retract: 0.0018673
displacement_range: 0.0092776

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9969581749e-05
# Encoder (count/step)
gain_step_to_count: 8.1905186885716
