---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "007"

# Load cell
cell_serial_number: "749021"
# Sensitivity (mV/V)
cell_sensitivity: 1.60612

# Encoder limit
encoder_limit_extend: 1748907
encoder_limit_retract: -1748907

# Displacement data (m)
displacement_limit_extend: 0.0107335
displacement_limit_retract: 0.0022058
displacement_range: 0.0085277

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9972530045e-05
# Encoder (count/step)
gain_step_to_count: 8.19029655064772
