---
# Actuator data

# Actuator model
model: "14902-1000"
actuator_serial_number: "015"

# Load cell
cell_serial_number: "748523"
# Sensitivity (mV/V)
cell_sensitivity: 1.61236

# Encoder limit
encoder_limit_extend: 1834050
encoder_limit_retract: -1834050

# Displacement data (m)
displacement_limit_extend: 0.0106073
displacement_limit_retract: 0.0016665
displacement_range: 0.0089408

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9964429231e-05
# Encoder (count/step)
gain_step_to_count: 8.18973954457508
