---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "018"

# Load cell
cell_serial_number: "749039"
# Sensitivity (mV/V)
cell_sensitivity: 1.58036

# Encoder limit
encoder_limit_extend: 1733837
encoder_limit_retract: -1733837

# Displacement data (m)
displacement_limit_extend: 0.0105943
displacement_limit_retract: 0.00214
displacement_range: 0.0084543

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9968666352e-05
# Encoder (count/step)
gain_step_to_count: 8.18928987561015
