---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "010"

# Load cell
cell_serial_number: "749028"
# Sensitivity (mV/V)
cell_sensitivity: 1.5803

# Encoder limit
encoder_limit_extend: 1765369
encoder_limit_retract: -1765369

# Displacement data (m)
displacement_limit_extend: 0.0106044
displacement_limit_retract: 0.001996
displacement_range: 0.0086084

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.996767708e-05
# Encoder (count/step)
gain_step_to_count: 8.19106248066811
