---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "011"

# Load cell
cell_serial_number: "749022"
# Sensitivity (mV/V)
cell_sensitivity: 1.59496

# Encoder limit
encoder_limit_extend: 1727275
encoder_limit_retract: -1727275

# Displacement data (m)
displacement_limit_extend: 0.0107102
displacement_limit_retract: 0.0022893
displacement_range: 0.0084209

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.996568313e-05
# Encoder (count/step)
gain_step_to_count: 8.18969531751124
