---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "001"

# Load cell
cell_serial_number: "748521"
# Sensitivity (mV/V)
cell_sensitivity: 1.60211

# Encoder limit
encoder_limit_extend: 1673218
encoder_limit_retract: -1673218

# Displacement data (m)
displacement_limit_extend: 0.0104669
displacement_limit_retract: 0.0023097
displacement_range: 0.0081572

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9967031173e-05
# Encoder (count/step)
gain_step_to_count: 8.19084054186386
