---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "011"

# Load cell
cell_serial_number: "750172"
# Sensitivity (mV/V)
cell_sensitivity: 1.59086

# Encoder limit
encoder_limit_extend: 1827488
encoder_limit_retract: -1828600

# Displacement data (m)
displacement_limit_extend: 0.0108083
displacement_limit_retract: 0.0018937
displacement_range: 0.0089146

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9967828618e-05
# Encoder (count/step)
gain_step_to_count: 8.18741285362394
