---
# Actuator data

# Actuator model
model: "14902-1000"
actuator_serial_number: "005"

# Load cell
cell_serial_number: "748508"
# Sensitivity (mV/V)
cell_sensitivity: 1.60135

# Encoder limit
encoder_limit_extend: 1741511
encoder_limit_retract: -1741511

# Displacement data (m)
displacement_limit_extend: 0.0104278
displacement_limit_retract: 0.0019323
displacement_range: 0.0084955

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9971482294e-05
# Encoder (count/step)
gain_step_to_count: 8.19086820247607
