---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "017"

# Load cell
cell_serial_number: "749037"
# Sensitivity (mV/V)
cell_sensitivity: 1.5694

# Encoder limit
encoder_limit_extend: 1911937
encoder_limit_retract: -1911937

# Displacement data (m)
displacement_limit_extend: 0.011126
displacement_limit_retract: 0.0018046
displacement_range: 0.0093214

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9970289959e-05
# Encoder (count/step)
gain_step_to_count: 8.19029995714896
