---
# Actuator data

# Actuator model
model: "14902-1000"
actuator_serial_number: "003"

# Load cell
cell_serial_number: "748515"
# Sensitivity (mV/V)
cell_sensitivity: 1.62689

# Encoder limit
encoder_limit_extend: 1761205
encoder_limit_retract: -1761205

# Displacement data (m)
displacement_limit_extend: 0.0104473
displacement_limit_retract: 0.0018612
displacement_range: 0.0085861

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9964330025e-05
# Encoder (count/step)
gain_step_to_count: 8.192129672716
