---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "012"

# Load cell
cell_serial_number: "748532"
# Sensitivity (mV/V)
cell_sensitivity: 1.61788

# Encoder limit
encoder_limit_extend: 1778067
encoder_limit_retract: -1778067

# Displacement data (m)
displacement_limit_extend: 0.0107908
displacement_limit_retract: 0.0021191
displacement_range: 0.0086717

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9973587224e-05
# Encoder (count/step)
gain_step_to_count: 8.18994932432432
