---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "017"

# Load cell
cell_serial_number: "749041"
# Sensitivity (mV/V)
cell_sensitivity: 1.59204

# Encoder limit
encoder_limit_extend: 1802243
encoder_limit_retract: -1803862

# Displacement data (m)
displacement_limit_extend: 0.0108556
displacement_limit_retract: 0.0020639
displacement_range: 0.0087917

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.996677766e-05
# Encoder (count/step)
gain_step_to_count: 8.18845693960952
