---
# Actuator data

# Actuator model
model: "14902-1000"
actuator_serial_number: "017"

# Load cell
cell_serial_number: "748519"
# Sensitivity (mV/V)
cell_sensitivity: 1.5694

# Encoder limit
encoder_limit_extend: 1738352
encoder_limit_retract: -1738352

# Displacement data (m)
displacement_limit_extend: 0.0103717
displacement_limit_retract: 0.0018994
displacement_range: 0.0084723

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9962112875e-05
# Encoder (count/step)
gain_step_to_count: 8.19099827071214
