---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "020"

# Load cell
cell_serial_number: "750185"
# Sensitivity (mV/V)
cell_sensitivity: 1.58814

# Encoder limit
encoder_limit_extend: 1769475
encoder_limit_retract: -1770267

# Displacement data (m)
displacement_limit_extend: 0.0106375
displacement_limit_retract: 0.0020052
displacement_range: 0.0086323

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9969294862e-05
# Encoder (count/step)
gain_step_to_count: 8.19068122203362
