---
# Actuator data

# Actuator model
model: "14902-1100"
actuator_serial_number: "019"

# Load cell
cell_serial_number: "749031"
# Sensitivity (mV/V)
cell_sensitivity: 1.58661

# Encoder limit
encoder_limit_extend: 1723591
encoder_limit_retract: -1723591

# Displacement data (m)
displacement_limit_extend: 0.0106848
displacement_limit_retract: 0.0022815
displacement_range: 0.0084033

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9966101695e-05
# Encoder (count/step)
gain_step_to_count: 8.18990654205609
