---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "030"

# Load cell
cell_serial_number: "748508"
# Sensitivity (mV/V)
cell_sensitivity: 1.60135

# Encoder limit
encoder_limit_extend: 1822973
encoder_limit_retract: -1819569

# Displacement data (m)
displacement_limit_extend: 0.0109038
displacement_limit_retract: 0.0020223
displacement_range: 0.0088815

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9975353959e-05
# Encoder (count/step)
gain_step_to_count: 8.19012809948313
