---
# Actuator data

# Actuator model
model: "14902-1000"
actuator_serial_number: "006"

# Load cell
cell_serial_number: "748507"
# Sensitivity (mV/V)
cell_sensitivity: 1.61464

# Encoder limit
encoder_limit_extend: 1619029
encoder_limit_retract: -1619029

# Displacement data (m)
displacement_limit_extend: 0.01002
displacement_limit_retract: 0.0021264
displacement_range: 0.0078936

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9964062764e-05
# Encoder (count/step)
gain_step_to_count: 8.18878501518734
