---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "024"

# Load cell
cell_serial_number: "750186"
# Sensitivity (mV/V)
cell_sensitivity: 1.59596

# Encoder limit
encoder_limit_extend: 1939063
encoder_limit_retract: -1930901

# Displacement data (m)
displacement_limit_extend: 0.0110847
displacement_limit_retract: 0.0016496
displacement_range: 0.0094351

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9969726838e-05
# Encoder (count/step)
gain_step_to_count: 8.18980780061956
