---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "019"

# Load cell
cell_serial_number: "750188"
# Sensitivity (mV/V)
cell_sensitivity: 1.59489

# Encoder limit
encoder_limit_extend: 1720320
encoder_limit_retract: -1721121

# Displacement data (m)
displacement_limit_extend: 0.0104751
displacement_limit_retract: 0.0020837
displacement_range: 0.0083914

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9968745042e-05
# Encoder (count/step)
gain_step_to_count: 8.18875297477389
