---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "026"

# Load cell
cell_serial_number: "750189"
# Sensitivity (mV/V)
cell_sensitivity: 1.60106

# Encoder limit
encoder_limit_extend: 1752965
encoder_limit_retract: -1752392

# Displacement data (m)
displacement_limit_extend: 0.0107677
displacement_limit_retract: 0.0022192
displacement_range: 0.0085485

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9973383143e-05
# Encoder (count/step)
gain_step_to_count: 8.18935637014548
