---
# Actuator data

# Actuator model
model: "14902-1200"
actuator_serial_number: "012"

# Load cell
cell_serial_number: "749044"
# Sensitivity (mV/V)
cell_sensitivity: 1.59745

# Encoder limit
encoder_limit_extend: 1888277
encoder_limit_retract: -1892331

# Displacement data (m)
displacement_limit_extend: 0.0109231
displacement_limit_retract: 0.0017043
displacement_range: 0.0092188

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 1.9969824155e-05
# Encoder (count/step)
gain_step_to_count: 8.18920037629352
