---
# Actuator data

# Actuator model
model: "14903-1000"
actuator_serial_number: "003"

# Load cell
cell_serial_number: "62434898"
# Sensitivity (mV/V)
cell_sensitivity: 2.999

# Encoder limit
encoder_limit_extend: 1247676
encoder_limit_retract: -1223028

# Displacement data (m)
displacement_limit_extend: 0.0009118
displacement_limit_retract: -0.0009334
displacement_range: 0.0018452

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 6.1559e-06
# Encoder (count/step)
gain_step_to_count: 8.196574
