---
# Actuator data

# Actuator model
model: "14903-1000"
actuator_serial_number: "006"

# Load cell
cell_serial_number: "70401273"
# Sensitivity (mV/V)
cell_sensitivity: 3.001

# Encoder limit
encoder_limit_extend: 1293513
encoder_limit_retract: -1266486

# Displacement data (m)
displacement_limit_extend: 0.0009285
displacement_limit_retract: -0.0009605
displacement_range: 0.001889

# Displacement gain

# Step (mm/step)
gain_step_to_mm: 6.09442060085837e-06
# Encoder (count/step)
gain_step_to_count: 8.18610157367668
