---
# Data acquisition (DAQ) parameters

# The frequency of DAQ loop in Hz.
frequency_loop: 20.0

# The frequency to toggle the closed-loop control bit in Hz. This frequency
# should be a divisor of frequency_loop.
frequency_toggle_bit: 10.0

# The limit of the actuator inner-loop controller (ILC) stale data. Sometimes,
# you may want to tune this parameter for the possible bad communication
# between the controller and ILC to avoid the trigger of error.
actuator_ilc_stale_data_limit: 10

# Bypassed actuator ILC list (0-based) to check the error reported by ILC
# directly. Any ILC in this list should be set to be hardpoint.
bypassed_actuator_ilcs: []

# NI FPGA bitfile name in the "fpga/" directory.
name_bitfile: "NiFpga_portSerialMasterSlave.lvbitx"

# NI specific FPGA header file name in the "fpga/" directory, which should be
# similar to the bitfile name.
name_header: "NiFpga_portSerialMasterSlave.h"

# Resource of the NI FPGA. You can find it from the LabVIEW project or NI MAX.
fpga_resource: "RIO0"

# The number of depth requested in the DAQ FIFO (power and digital input
# data). The number of elements for each data writing in FPGA loop is 9. Note
# the actual depth of the FIFO might be larger than this value, which depends
# on the FPGA design. 
requested_depth_in_fifo_daq: 90

# The number of depth requested in the inbound and outbound FIFOs for the ILC
# communication. Note the actual depth of the FIFO might be larger than this
# value, which depends on the FPGA design. 
requested_depth_in_fifo_inbound_outbound: 1023

# Buffer time to clear the DAQ FIFO in milliseconds.
buffer_time_to_clear_fifo_daq: 5

# Pace to write the data to ILC in ticks. The tick is the unit of time in
# FPGA, which is determined by the FPGA design.
write_fifo_pace_ticks: 1

# Timeout for the interrupt request (IRQ) in milliseconds.
timeout_irq: 50
