---
# Data acquisition (DAQ) parameters

# The frequency of DAQ loop in Hz.
frequency_loop: 20.0

# The frequency to toggle the closed-loop control bit in Hz. This frequency
# should be a divisor of frequency_loop.
frequency_toggle_bit: 10.0

# The limit of the inner-loop controller (ILC) stale data. Sometimes, you may
# want to tune this parameter for the possible bad communication between the
# controller and ILC to avoid the trigger of error.
ilc_stale_data_limit: 10

# Bypassed actuator ILC list (0-based) to check the error reported by ILC
# directly. Any ILC in this list should be set to be hardpoint.
bypassed_actuator_ilcs: []

# Bypass the check of the stale data for inclinometer. This is used for the
# inclinometer with bad communication, which can cause the stale data error.
# Remove this after we fix the ILC of the inclinometer to avoid the stale data
# error.
bypass_check_stale_inclinometer: true

# Sleep time in microseconds to wait for the ILC action after broadcasting the
# global command to all ILCs.
sleep_time_broadcast_ilc: 400

# Sleep time in microseconds to wait for the ILC to be ready for the next
# command.
sleep_time_ilc_reading: 10

# NI FPGA bitfile name in the "fpga/" directory.
name_bitfile: "NiFpga_portSerialMasterSlave.lvbitx"

# NI specific FPGA header file name in the "fpga/" directory, which should be
# similar to the bitfile name.
name_header: "NiFpga_portSerialMasterSlave.h"

# Resource of the NI FPGA. You can find it from the LabVIEW project or NI MAX.
fpga_resource: "RIO0"

# The number of depth requested in the DAQ FIFO (power and digital input
# data). The number of elements for each data writing in FPGA loop is 9. Note
# the actual depth of the FIFO might be larger than this value, which depends
# on the FPGA design. 
requested_depth_in_fifo_daq: 90

# The number of depth requested in the inbound and outbound FIFOs for the ILC
# communication. Note the actual depth of the FIFO might be larger than this
# value, which depends on the FPGA design. 
requested_depth_in_fifo_inbound_outbound: 1023

# Buffer time to clear the DAQ FIFO in milliseconds.
buffer_time_to_clear_fifo_daq: 5

# Pace to write the data to ILC in ticks. The tick is the unit of time in
# FPGA, which is determined by the FPGA design.
write_fifo_pace_ticks: 1

# Timeout for the interrupt request (IRQ) in milliseconds.
timeout_irq: 50

# Timeout to get the next character from the ILC in microseconds.
timeout_get_next_character: 60

# Payload number of bytes to set/get the ILC mode. This does not contain the
# bytes of cyclic redundancy check (CRC).
payload_byte_ilc_mode: 4

# Payload number of bytes to get the force and status. This does not contain
# the bytes of CRC.
payload_byte_get_force_and_status: 11

# Payload number of bytes to get the temperature values. This does not contain
# the bytes of CRC.
payload_byte_get_temperature: 18

# Payload number of bytes to get the displacement values. This does not contain
# the bytes of CRC.
payload_byte_get_displacement: 50

# Payload number of bytes to get the inclinometer value. This does not contain
# the bytes of CRC.
payload_byte_get_inclinometer: 6

# Latency to set/get the ILC mode in microseconds to wait for the first
# character from the response of ILC.
latency_ilc_mode: 320

# Latency to get the force and status in microseconds to wait for the first
# character from the response of ILC.
latency_get_force_and_status: 150

# Latency to get the temperature values in microseconds to wait for the first
# character from the response of ILC.
latency_get_temperature: 350

# Latency to get the displacement values in microseconds to wait for the first
# character from the response of ILC.
latency_get_displacement: 800

# Latency to get the inclinometer value in microseconds to wait for the first
# character from the response of ILC.
latency_get_inclinometer: 200
