---
# Application parameters

# Log the local telemetry file or not. This logs the power and control loop
# telemetry to a local file when the closed-loop control mode is not Idle.
# The timestamp (in milliseconds) is based on the starting time of the
# application to make the data easier to analyze.
local_telemetry_file: false

# Maximum number of local telemetry files to keep.
local_telemetry_max_files: 5

# Maximum number of bytes to keep in the local telemetry file. If the file size
# exceeds this limit, the file will be rotated.
local_telemetry_bytes_limit: 500000000

# Local telemetry file basename.
local_telemetry_basename: "telemetry.bin"

# Command and telemetry ports for the GUI (graphical user interface) and
# CSC (commandable SAL component) clients
port_command_gui: 50010
port_telemetry_gui: 50011

port_command_csc: 50000
port_telemetry_csc: 50001

# Timeout in milliseconds
timeout: 50

# Is the application running in the mirror mode? If not, it is running with the
# surrogate. The main difference is the control parameters.
is_mirror: true

# Look-up table (LUT) directory under the "config/lut/" directory.
lut: "optical"

# Number of digits for the telemetry
telemetry_digit: 2

# Log file directory.
log_directory: "log"

# Log file basename.
log_basename: "application"

# Log file suffix.
log_suffix: "log"

# File size in bytes to rotate the log file. 
log_size: 100000000

# Log files are kept for the specified number of days. Older files are deleted.
log_file_keep_days: 3

# Sleep time in seconds to wait for the LabVIEW startup execution to finish.
# This is only meaningful when the application is running with the hardware
# mode.
sleep_time_wait_for_labview: 30

# Path of the errlog.txt of the LabVIEW startup execution.
# This is used to get the FPGA bitfile loading status and the safety module
# status.
labview_errlog_path: "/var/local/natinst/log/errlog.txt"
